colorscheme habamax
set number relativenumber
syntax on

set shiftwidth=4
set textwidth=80
set expandtab
filetype plugin indent on
set autoindent smartindent

set incsearch
set cursorline
set cursorlineopt=number
set ignorecase smartcase

set noswapfile
set hidden
set wildmenu
set wildoptions=fuzzy
set wildignore=*.git/*

set shm+=I
set shm-=S
set history=500

let mapleader = ' '

nmap <silent><leader>h :term<cr>

nmap <silent> _ :Ex<cr>
nmap <leader><leader> <C-^>

vmap <c-r> c<c-r>=<c-r>"
vmap * "ay/\V<c-r>a<cr>
vmap # "ay?\V<c-r>a<cr>

nmap =ap ma=ap`a
vmap <leader>y "+y
vmap <leader>d "_d
nmap Q <nop>
nmap - <nop>
vmap <c-n> :m '>+1<CR>gv
vmap <c-p> :m '<-2<CR>gv

nnoremap <leader>gs :%s/\<<C-r><C-w>\>//gI<Left><Left><Left>
nnoremap <leader>s :s/\<<C-r><C-w>\>//gI<Left><Left><Left>

nmap <leader>p :<up><cr>
cmap <c-p> <up>
cmap <c-n> <down>

map  <F4> :bd!<cr>
map  <F7> :cp <cr>
map  <F8> :cn <cr>

"emacs
nmap <c-f> <nop>
nmap <c-b> <nop>
inoremap <c-f> <right>
inoremap <c-b> <left>
inoremap <c-d> <del>
inoremap <c-k> <c-o>D

if has('android')
    set path=.,$PREFIX/include,,
endif

runtime ftplugin/man.vim
packadd! comment
vmap <c-c> gc

highlight ExtraWhitespace ctermbg=204 guibg=#eb6f92
match ExtraWhitespace /\s\+$/
